// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTn911ktpmUmCQbu43TeeghZR5sfZwNtI',
    appId: '1:424730266680:web:d7b564012266adfff1aacd',
    messagingSenderId: '424730266680',
    projectId: 'social-b14d5',
    authDomain: 'social-b14d5.firebaseapp.com',
    storageBucket: 'social-b14d5.appspot.com',
    measurementId: 'G-JDHSNY9FDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpOV8Ye18XBwdoAimwlEdVr7uqCY-mCE',
    appId: '1:424730266680:android:6eb223b8fe05d7f8f1aacd',
    messagingSenderId: '424730266680',
    projectId: 'social-b14d5',
    storageBucket: 'social-b14d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtraoNPDeYDcZQA17VBXZ5RLPnFEMD690',
    appId: '1:424730266680:ios:ad6cd1d8c336e536f1aacd',
    messagingSenderId: '424730266680',
    projectId: 'social-b14d5',
    storageBucket: 'social-b14d5.appspot.com',
    iosClientId: '424730266680-47dbkn53ngbbab6jvn6tahgvo1cbi408.apps.googleusercontent.com',
    iosBundleId: 'org.alexwayne.social',
  );
}
